export enum CodigoTipoVeiculoEnum {
    CICLOMOTOR = "2",
    MOTONETA = "3",
    MOTOCICLETA = "4",
    TRICICLO = "5",
    AUTOMOVEL = "6",
    MICRO_ONIBUS = "7",
    ONIBUS = "8",
    REBOQUE = "10",
    SEMI_REBOQUE = "11",
    CAMIONETA = "13",
    CAMINHAO = "14",
    CAMINHAO_TRATOR = "17",
    TRATOR_DE_RODAS = "18",
    TRATOR_DE_ESTEIRAS = "19",
    TRATOR_MISTO = "20",
    QUADRICICLO = "21",
    CHASSI_PLATAFORMA = "22",
    CAMINHONETE = "23",
    UTILITARIO = "25",
    MOTOR_HOME = "26",
    SEM_TIPO = "100"
}

export const CodigoTipoVeiculoDescricao = [
    { value: CodigoTipoVeiculoEnum.CICLOMOTOR, key: "CICLOMOTOR", label: 'Ciclomotor' },
    { value: CodigoTipoVeiculoEnum.MOTONETA, key: "MOTONETA", label: 'Motoneta' },
    { value: CodigoTipoVeiculoEnum.MOTOCICLETA, key: "MOTOCICLETA", label: 'Motocicleta' },
    { value: CodigoTipoVeiculoEnum.TRICICLO, key: "TRICICLO", label: 'Triciclo' },
    { value: CodigoTipoVeiculoEnum.AUTOMOVEL, key: "AUTOMOVEL", label: 'Automóvel' },
    { value: CodigoTipoVeiculoEnum.MICRO_ONIBUS, key: "MICRO_ONIBUS", label: 'Micro Ônibus' },
    { value: CodigoTipoVeiculoEnum.ONIBUS, key: "ONIBUS", label: 'Ônibus' },
    { value: CodigoTipoVeiculoEnum.REBOQUE, key: "REBOQUE", label: 'Reboque' },
    { value: CodigoTipoVeiculoEnum.SEMI_REBOQUE, key: "SEMI_REBOQUE", label: 'Semi Reboque' },
    { value: CodigoTipoVeiculoEnum.CAMIONETA, key: "CAMIONETA", label: 'Camioneta' },
    { value: CodigoTipoVeiculoEnum.CAMINHAO, key: "CAMINHAO", label: 'Caminhão' },
    { value: CodigoTipoVeiculoEnum.CAMINHAO_TRATOR, key: "CAMINHAO_TRATOR", label: 'Caminhão Trator' },
    { value: CodigoTipoVeiculoEnum.TRATOR_DE_RODAS, key: "TRATOR_DE_RODAS", label: 'Trator de Rodas' },
    { value: CodigoTipoVeiculoEnum.TRATOR_DE_ESTEIRAS, key: "TRATOR_DE_ESTEIRAS", label: 'Trator de Esteiras' },
    { value: CodigoTipoVeiculoEnum.TRATOR_MISTO, key: "TRATOR_MISTO", label: 'Trator Misto' },
    { value: CodigoTipoVeiculoEnum.QUADRICICLO, key: "QUADRICICLO", label: 'Quadriciclo' },
    { value: CodigoTipoVeiculoEnum.CHASSI_PLATAFORMA, key: "CHASSI_PLATAFORMA", label: 'Chassi Plataforma' },
    { value: CodigoTipoVeiculoEnum.CAMINHONETE, key: "CAMINHONETE", label: 'Caminhonete' },
    { value: CodigoTipoVeiculoEnum.UTILITARIO, key: "UTILITARIO", label: 'Utilitário' },
    { value: CodigoTipoVeiculoEnum.MOTOR_HOME, key: "MOTOR_HOME", label: 'Motor Home' },
    { value: CodigoTipoVeiculoEnum.SEM_TIPO, key: "SEM_TIPO", label: 'Sem Tipo' }
];

export const CodigoTipoVeiculoId = [
    { value: 2, key: "CICLOMOTOR", label: 'Ciclomotor' },
    { value: 3, key: "MOTONETA", label: 'Motoneta' },
    { value: 4, key: "MOTOCICLETA", label: 'Motocicleta' },
    { value: 5, key: "TRICICLO", label: 'Triciclo' },
    { value: 6, key: "AUTOMOVEL", label: 'Automóvel' },
    { value: 7, key: "MICRO_ONIBUS", label: 'Micro Ônibus' },
    { value: 8, key: "ONIBUS", label: 'Ônibus' },
    { value: 10, key: "REBOQUE", label: 'Reboque' },
    { value: 11, key: "SEMI_REBOQUE", label: 'Semi Reboque' },
    { value: 13, key: "CAMIONETA", label: 'Camioneta' },
    { value: 14, key: "CAMINHAO", label: 'Caminhão' },
    { value: 17, key: "CAMINHAO_TRATOR", label: 'Caminhão Trator' },
    { value: 18, key: "TRATOR_DE_RODAS", label: 'Trator de Rodas' },
    { value: 19, key: "TRATOR_DE_ESTEIRAS", label: 'Trator de Esteiras' },
    { value: 20, key: "TRATOR_MISTO", label: 'Trator Misto' },
    { value: 21, key: "QUADRICICLO", label: 'Quadriciclo' },
    { value: 22, key: "CHASSI_PLATAFORMA", label: 'Chassi Plataforma' },
    { value: 23, key: "CAMINHONETE", label: 'Caminhonete' },
    { value: 25, key: "UTILITARIO", label: 'Utilitário' },
    { value: 26, key: "MOTOR_HOME", label: 'Motor Home' },
    { value: 100, key: "SEM_TIPO", label: 'Sem Tipo' }
];
